### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by ben-manes** [cbeust/testng#1168]
When running a test class using `6.9.13.8` the tests pass, but the following error is printed. This does not occur in `6.9.12`. (Running via Eclipse)

```
[TestNG] Reporter org.testng.reporters.JUnitReportReporter@2b552920 failed
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at org.testng.reporters.JUnitReportReporter.getNextConfiguration(JUnitReportReporter.java:220)
	at org.testng.reporters.JUnitReportReporter.generateReport(JUnitReportReporter.java:105)
	at org.testng.TestNG.generateReports(TestNG.java:1175)
	at org.testng.TestNG.run(TestNG.java:1102)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
```

**Comment by ben-manes** [comment]
The problem is that the `removeAll` is accidentally within the loop body.

```java
for (ITestResult r : confResults) {
  if (! seen.containsKey(r.getMethod())) {
    result += r.getEndMillis() - r.getStartMillis();
    seen.put(r.getMethod(), r);
  }
  confResults.removeAll(seen.values());
}
```

**Comment by cbeust** [comment]
Good catch. Would you be willing to send a PR?

-- 
Cédric

**Comment by shabana-parveen** [comment]
when will we expect the issue fixed release? as I am also getting the same issue.

**Comment by missedone** [comment]
hi @shabana-parveen 
the fix is available in 6.9.13.8 on jCenter.

**Comment by shabana-parveen** [comment]
Thanks @missedone

**Comment by azell** [comment]
Still seeing the error with 6.9.13.8 and u102:

```
Running TestSuite
[TestNG] Reporter org.testng.reporters.JUnitReportReporter@6e4de19b failed
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at org.testng.reporters.JUnitReportReporter.getNextConfiguration(JUnitReportReporter.java:220)
	at org.testng.reporters.JUnitReportReporter.generateReport(JUnitReportReporter.java:105)
	at org.testng.TestNG.generateReports(TestNG.java:1175)
	at org.testng.TestNG.run(TestNG.java:1102)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:147)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
```

POM:

```
      <dependency>
        <groupId>org.testng</groupId>
        <artifactId>testng</artifactId>
        <version>6.9.13.8</version>
      </dependency>
```

**Comment by ben-manes** [comment]
I don't see my fix in `6.9.13.8` (viewed from source jar). So while .8 was released that day, its probably from an earlier commit.

**Comment by gdemecki** [comment]
Exactly. This issue is still present in the version `6.9.13.8`.

**Comment by shabana-parveen** [comment]
Yes, I can also se the same

**Comment by jnyman** [comment]
This issue appears to be closed but I, like others, are still seeing the issue. Just making sure that folks area aware this is still a problem, including with the 6.9.13.8 release.

**Comment by juherr** [comment]
The fix should be available in the next release.

**Comment by randy-li** [comment]
When shall we release next version. See the problem on 6.9.13.8 with Eclipse. Thanks!

**Comment by kodayashi** [comment]
Hi there. Any ETA on a release vehicle that contains this fix? I'm stuck on this release due to a fix that I need in 6.9.13.x :)

**Comment by krmahadevan** [comment]
@kodayashi - The latest version of TestNG viz., 6.10 is already available in bintray.

You can just add the following and you should be able to consume it 

```xml
<repositories>
    <repository>
        <id>bintray-cbeust-maven</id>
        <name>bintray</name>
        <url>http://dl.bintray.com/cbeust/maven</url>
    </repository>
</repositories>
<dependencies>
    <dependency>
        <groupId>org.testng</groupId>
        <artifactId>testng</artifactId>
        <version>6.9.13.8</version>
    </dependency>
</dependencies>
```

**Comment by forresthopkinsa** [comment]
Is 6.10 stable? Production ready?

**Comment by krmahadevan** [comment]
Not sure what you mean by "Production ready" ? A released product is meant to be stable consumable no ?

**Comment by forresthopkinsa** [comment]
I'm asking if this is a Beta you're suggesting

**Comment by krmahadevan** [comment]
No this is not a beta. This is a released version of TestNG.

**Comment by forresthopkinsa** [comment]
Cool, thanks. Is there a timeline for when it will be in Eclipse's repositories?

**Comment by krmahadevan** [comment]
@cbeust should be able to answer that. I know he mentioned he is going to be pushing the changes to Maven Central as well.

**Comment by cbeust** [comment]
6.10 is available in the main JCenter, no need to point to my personal repo.

**Comment by dpinol** [comment]
Why is it not uploaded anymore to mvnrepository.com nor http://search.maven.org/ since 6.9.13.6?

**Comment by juherr** [comment]
Not yet but it is in progress

**Comment by cbeust** [comment]
And right now, JCenter is failing to synchronize to Maven and telling me to try again later... sigh.

**Comment by kiherrold** [comment]
I am new to TestNG and am trying to pick up this new version but the instructions I've found don't appear to work for installing the jar in Eclipse Neon.  Is an updated plub-in going to be on the Marketplace soon?  Or can someone point me good instructions for installing from a jar?   Thanks in advance.

**Comment by missedone** [comment]
@kiherrold , you can install the latest beta version (6.10.x) of TestNG Eclipse Plugin, it has TestNG 6.10 embedded.
updatesite for beta: http://testng.org/eclipse-beta
detail instructions: http://testng.org/doc/download.html

**Comment by forresthopkinsa** [comment]
Lol, so is it a Beta after all? Someone enlighten me

**Comment by missedone** [comment]
TestNG 6.10 is released.
TestNG Eclipse Plugin 6.10.x is still in beta, will be released in any seconds.

**Comment by kodayashi** [comment]
Sweet, thanks everyone!

**Comment by forresthopkinsa** [comment]
Neat. Good work folks

**Comment by missedone** [comment]
TestNG Eclipse Plugin 6.10.0.201612030230 is released.

**Comment by galan** [comment]
When will 6.10.x be available from the Maven Central?
http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.testng%22%20AND%20a%3A%22testng%22

**Comment by juherr** [comment]
@galan https://github.com/cbeust/testng/issues/1261

**Comment by sbabcoc** [comment]
The 6.10.x release that will contain the fix for this issue has still not been posted yet. When can we expect this to be available?

**Comment by missedone** [comment]
@sbabcoc 
TestNG 6.10 is available both on [Maven Central](http://search.maven.org/#artifactdetails%7Corg.testng%7Ctestng%7C6.10%7Cjar) and jCenter.
TestNG Eclipse Plugin 6.10.0.201612030230 is available on the [release update site](http://beust.com/eclipse)

**Comment by sbabcoc** [comment]
I upgraded to TestNG 6.10.0.201612030230, and this issue still exists.

**Comment by missedone** [comment]
@sbabcoc , Eclipse Plugin simply respects the testng jar version of your project, so could you check the testng version on your project classpath? make sure that's up to date.

**Comment by anand853** [comment]
still i hit the same problem with testng 6.10. can you please share the workaround on this?

**Comment by juherr** [comment]
@anand853 Could you share your stacktrace? I bet the issue is not the same but a similar one.

**Comment by anand853** [comment]
@juherr ,please find the logs

Tests run: 331, Failures: 5, Errors: 0, Skipped: 0, Time elapsed: 1,082.119 sec <<< FAILURE!
test62(test.com.t.test.com.t.AppRoombaHelpTest)  Time elapsed: 0.01 sec  <<< FAILURE!
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.relevantcodes.extentreports.model.Test.trackLastRunStatus(Test.java:389)
	at com.relevantcodes.extentreports.ExtentTest.log(ExtentTest.java:101)
	at com.relevantcodes.extentreports.ExtentTest.log(ExtentTest.java:180)
	at test.com.t.sitecores.curlHelpRoomba(sitecores.java:1475)
	at test.com.t.test.com.t.AppRoombaHelpTest.test62(AppRoombaHelpTest.java:610)

test73(test.com.t.test.com.t.AppBraavaTermsTest)  Time elapsed: 0 sec  <<< FAILURE!
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.relevantcodes.extentreports.model.Test.trackLastRunStatus(Test.java:389)
	at com.relevantcodes.extentreports.ExtentTest.log(ExtentTest.java:101)
	at com.relevantcodes.extentreports.ExtentTest.log(ExtentTest.java:180)
	at test.com.t.test.com.t.AppBraavaTermsTest.test73(AppBraavaTermsTest.java:604)

test77(test.com.t.test.com.t.AppBraavaTermsTest)  Time elapsed: 0.169 sec  <<< FAILURE!
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:451)
	at org.json.JSONObject.<init>(JSONObject.java:195)
	at org.json.JSONObject.<init>(JSONObject.java:319)
	at test.com.t.sitecores.curlBraavaTermsBase(sitecores.java:1222)
	at test.com.t.sitecores.curlBraavaTerms(sitecores.java:1187)
	at test.com.t.test.com.t.AppBraavaTermsTest.test77(AppBraavaTermsTest.java:632)

test76(test.com.t.test.com.t.AppBraavaTermsTest)  Time elapsed: 0.17 sec  <<< FAILURE!
java.lang.NullPointerException: null
	at com.relevantcodes.extentreports.model.Test.trackLastRunStatus(Test.java:390)
	at com.relevantcodes.extentreports.ExtentTest.log(ExtentTest.java:101)
	at com.relevantcodes.extentreports.ExtentTest.log(ExtentTest.java:180)
	at test.com.t.sitecores.curlBraavaTerms(sitecores.java:1188)
	at test.com.t.test.com.t.AppBraavaTermsTest.test76(AppBraavaTermsTest.java:626)

test66(test.com.t.test.com.t.AppBraavaTermsTest)  Time elapsed: 0.17 sec  <<< FAILURE!
java.lang.NullPointerException: null
	at com.relevantcodes.extentreports.model.Test.trackLastRunStatus(Test.java:390)
	at com.relevantcodes.extentreports.ExtentTest.log(ExtentTest.java:101)
	at com.relevantcodes.extentreports.ExtentTest.log(ExtentTest.java:180)
	at test.com.t.sitecores.curlBraavaTerms(sitecores.java:1188)
	at test.com.t.test.com.t.AppBraavaTermsTest.test66(AppBraavaTermsTest.java:549)


Results :

Failed tests: 
  AppRoombaHelpTest.test62:610 » ConcurrentModification
  AppBraavaTermsTest.test73:604 » ConcurrentModification
  AppBraavaTermsTest.test77:632 » JSON A JSONObject text must begin with '{' at ...
  AppBraavaTermsTest.test76:626 » NullPointer
  AppBraavaTermsTest.test66:549 » NullPointer

Tests run: 331, Failures: 5, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18:04 min
[INFO] Finished at: 2017-02-09T09:45:25-05:00
[INFO] Final Memory: 20M/316M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.14.1:test (default-test) on project com.sitecore.irobot: There are test failures.
[ERROR]

**Comment by krmahadevan** [comment]
@anand853 - This is not a problem from TestNG. Looks like you are facing this problem from extent reports, to be specific [this method](https://github.com/anshooarora/extentreports-java/blob/2.41.2/src/main/java/com/relevantcodes/extentreports/model/Test.java#L388-L396). I would suggest that you please file a bug [here](https://github.com/anshooarora/extentreports-java/issues)

**Comment by anand853** [comment]
@krmahadevan ,
can you please provide me any workaround on this?

**Comment by krmahadevan** [comment]
@anand853 - There are no work arounds for this. Extent Reports needs to fix itself so that it doesn't try to modify and iterate a List at the same time without any sort of synchronization mechanism that wraps access to the list. That would ensure that you don't see this exception from extent reports. Not much can be done, apart from fixing the problematic code.

**Comment by juherr** [comment]
For reference: https://github.com/anshooarora/extentreports-java/issues/769

**Comment by anand853** [comment]
with the testng also im getting same error, can you please let us know which version of the jar and how to achieve parallel execution with testNG

error
java.util.ConcurrentModificationException
	at test.com.t.social.A.es_(A.java:1049)


Results :

Failed tests: 
  AA.es_:1049 » ConcurrentModification

Tests run: 260, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 55:11 min
[INFO] Finished at: 2017-03-10T10:50:25-05:00
[INFO] Final Memory: 22M/370M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project bot: There are test failures.
[ERROR] 
[ERROR] Please refer to svalidation/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by juherr** [comment]
@anand853 

> java.util.ConcurrentModificationException
> at test.com.t.social.A.es_(A.java:1049)

It looks the exception comes from the test itself and not TestNG

**Comment by kanandhapriya** [comment]
Hi all, 

I am using testng-version 7.1.0, getting concurrentModificationException in following line.
My Code: ExtentManager.getTestStep().log(Status.INFO, m);

Error:
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at com.aventstack.extentreports.ExtentObservable.collectRunInfo(ExtentObservable.java:465)
	at com.aventstack.extentreports.ExtentObservable.addLog(ExtentObservable.java:309)
	at com.aventstack.extentreports.ExtentTest.addLog(ExtentTest.java:359)
	at com.aventstack.extentreports.ExtentTest.log(ExtentTest.java:308)
	at com.aventstack.extentreports.ExtentTest.log(ExtentTest.java:333)
	at com.aventstack.extentreports.ExtentTest.log(ExtentTest.java:352)

Note: i use DataProvider, Multithreading.

**Comment by juherr** [comment]
@kanandhapriya Your issue comes from com.aventstack.extentreports. You should open an issue there https://github.com/extent-framework/extentreports-java

**Comment by forresthopkinsa** [comment]
Jeez, talk about necro
