### ISSUE TITLE
Error while using TestNg DataProvider must return either Object[][] or Iterator<Object>[], not class [[Ljava.lang.Object;

### ISSUE THREAD

**Issue by sajalsinghji** [cbeust/testng#1364]
### TestNG Version:6.10
> Note: only the latest version is supported

### Expected behavior
Testcase Should run using DataProvider data

### Actual behavior
Getting error : **Error while using TestNg DataProvider must return either Object[][] or Iterator<Object>[], not class [[Ljava.lang.Object;**

### Is the issue reproductible on runner?

[ Yes] Maven
[ Yes] Eclipse
[ Yes] IntelliJ

[http://stackoverflow.com/questions/42505444/error-while-using-testng-dataprovider-must-return-either-object-or-iterator?noredirect=1#comment72149743_42505444](url)

### Test case sample
```
public class LoginTest  {
	LoginPage page=new LoginPage();
	

	@Test(dataProvider="ExcelDataProvider",dataProviderClass=TestDataProvider.class)
	public void Logintest(String username,String password){
		
	//page.login("user@phptravels.com","demouser");
	page.login(username,password);
		
	}


	@AfterTest
	public void TearDown(){
		TestUtil.quit();
	}
}
```
```
  DataProvider: 
       public class TestDataProvider {
	static ExcelReader reader=new ExcelReader();
	@DataProvider(name="ExcelDataProvider")
        public static Object[][] ExcelDataProvider()
       {
		Object [][] rest = reader.readDataExcel("UserLogin");
		for(Object o:rest){
			System.out.println(o.toString());
		}
		return rest;
    }
 }
```
ExcelReader:
 ```
public class ExcelReader {

	static String fileName="Testdata";
	public String[][] readDataExcel(String TableName){
		String filePath="F:\\TravelSite\\TravelSiteAutomation\\Testdata.xlsx";
		File file =new File(filePath);
		
		
		try{
		FileInputStream stream=new FileInputStream(file);
		      Workbook workbook  = new XSSFWorkbook(stream);
		      XSSFSheet sheet=(XSSFSheet) workbook.getSheet("UnitTest");
		    	 List<XSSFTable> tables = sheet.getTables();
		    	 
		    	 for(XSSFTable table:tables){
		    		 String name=table.getName();
		    		 if(name.equals(TableName)){
		    			 
		    			 
		    			 int ci=0,cj=0;
		 		    	int rowNum=sheet.getLastRowNum()-sheet.getFirstRowNum();
		 		    	//System.out.println(rowNum);
		 		    	
		 		    	
		 		    	String[][] dataArray=new String[rowNum][100];
		 		    	for(int i = 1; i < rowNum+1; i++) {
		                    
		 		            Row row = sheet.getRow(i);
		 		        	
		 		            

		 		            //Create a loop to print cell values in a row
		 		            int colNum=row.getLastCellNum();
		 		           // System.out.println(colNum);
		 		            for(int j = 0; j <colNum; j++) {
		                           
		 		            	
		 		                //Print excel data in console
		                          Cell cell=row.getCell(j);
		                          DataFormatter formatter = new DataFormatter();
		                          String var_name = formatter.formatCellValue(cell);
		 		               System.out.print(var_name+" || ");
		 		               dataArray[ci][cj]=var_name;
		 		               
		 		            }
		                     
		 		            System.out.println();
		 		           }
		 		    	workbook.close();

		 		return dataArray;	
		 		    	}	
		    			 
		    		 }
		    	 Log.info("Table name is incorrect");
		    	 return null;
		    	 }
		    	 
		    	
		    			
		    catch(Exception e)
		
		{
		    	Log.debug(e.getMessage());
		    	
		    	
		    	return null;
		    }
		}
	}
```

**Comment by krmahadevan** [comment]
@sajalsinghji - Can you also please include the spreadsheet with which you are working ? that way it would be a bit more easy to run your sample and reproduce the issue.

**Comment by sajalsinghji** [comment]
[Testdata.xlsx](https://github.com/cbeust/testng/files/806550/Testdata.xlsx)

**Comment by jankowskirobert** [comment]
There is nothing wrong with testng. You have bug in your Excel parser but it's not domain of this repository and topic. 
The simplest way to check if it's a testng bug or not:
`import org.testng.annotations.AfterTest;
import org.testng.annotations.Test;

public class LoginTest {

	@Test(dataProvider = "ExcelDataProvider", dataProviderClass = TestDataProvider.class)
	public void Logintest(String username, String password) {

		// page.login("user@phptravels.com","demouser");
		System.out.println(username + " " + password);

	}

	@AfterTest
	public void TearDown() {

	}
}`
`import org.testng.annotations.DataProvider;

public class TestDataProvider {
	static ExcelReader reader = new ExcelReader();

	@DataProvider(name = "ExcelDataProvider")
	public static Object[][] ExcelDataProvider() {
		// ExcelReader reader = new ExcelReader();
		Object[][] rest = reader.readDataExcel("UserLogin");
		for (Object o : rest) {
			System.out.println(o.toString());
		}
		return rest;
	}
}`
`import java.io.File;
import java.io.FileInputStream;

public class ExcelReader {

	public String[][] readDataExcel(String TableName) {
		return new String[][] { { "aa", "ab" }, { "ba", "bb" } };
	}
}`

And result:

> [Ljava.lang.String;@6093dd95
[Ljava.lang.String;@5622fdf
aa ab
ba bb
PASSED: Logintest("aa", "ab")
PASSED: Logintest("ba", "bb")

===============================================
    Default test
    Tests run: 2, Failures: 0, Skips: 0
===============================================


===============================================
Default suite
Total tests run: 2, Failures: 0, Skips: 0
===============================================

[TestNG] Time taken by org.testng.reporters.EmailableReporter2@67784306: 9 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@3b0143d3: 53 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@1f28c152: 11 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 0 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@1d16f93d: 8 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@1c3a4799: 58 ms

**Comment by juherr** [comment]
@jankowskirobert I'm not sure it is a parser issue. The error message is provided by TestNG (https://github.com/cbeust/testng/blob/15a824bd8d3658e7070b7cf105f2adc011d07000/src/main/java/org/testng/internal/MethodInvocationHelper.java#L136) and the java compiler should have checked type.
I'd like to understand how it is possible to reach this unexpected issue and that's why I asked to open the issue.

@sajalsinghji Do you confirm the bug is fixed now?

@krmahadevan Are you able to reproduce?

**Comment by sajalsinghji** [comment]
@jankowskirobert  i am still facing the issue, but it really seems something is wrong with my excel return type, i am still trying to debug it.

**Comment by krmahadevan** [comment]
@juherr - I haven't yet reproduced it. Still at work. Will give it a try once I go home.

**Comment by juherr** [comment]
@sajalsinghji Ok, let us know

@krmahadevan Ok, no prob :)

**Comment by cbeust** [comment]
My suggestion to track this down: first of all, remove Excel out of the equation and return a hardcoded version of what your code should return.

Once you got this working, compare that return value with the one you are returning when calling the Excel API. I bet you'll find these two are not exactly the same type.

And yes, it's a bit tricky to manipulate `Object[][]` but it's the only way to achieve this in Java.

**Comment by krmahadevan** [comment]
@juherr - This is not a problem with TestNG. I tracked the problem. It was indeed an issue with the `ExcelParser`

@sajalsinghji - Please use the below version for your test (and it should work fine)

```java
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.DataFormatter;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFTable;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.util.ArrayList;
import java.util.List;

public class ExcelReader {

    public static String[][] readDataExcel(String TableName) {
        String filePath = "src/test/resources/Testdata.xlsx";
        try {
            Workbook workbook = new XSSFWorkbook(filePath);
            XSSFSheet sheet = (XSSFSheet) workbook.getSheet("UnitTest");
            List<XSSFTable> tables = sheet.getTables();

            for (XSSFTable table : tables) {
                String name = table.getName();
                if (! name.equals(TableName)) {
                    continue;
                }
                int rowCount = sheet.getLastRowNum() - sheet.getFirstRowNum();
                System.out.println(rowCount);
                int columnCount = - 1;
                List<List<String>> data = new ArrayList<>();
                for (int i = 1; i < rowCount + 1; i++) {
                    Row row = sheet.getRow(i);
                    int colNum = row.getLastCellNum();
                    if (columnCount == - 1) {
                        columnCount = colNum;
                    }
                    List<String> rowData = new ArrayList<>();
                    for (int j = 0; j < colNum; j++) {
                        Cell cell = row.getCell(j);
                        DataFormatter formatter = new DataFormatter();
                        String var_name = formatter.formatCellValue(cell);
                        if (var_name != null && ! var_name.trim().isEmpty()) {
                            rowData.add(var_name);
                        }
                    }
                    if (! rowData.isEmpty()) {
                        data.add(rowData);
                    }
                }
                workbook.close();
                String[][] dataArray = new String[rowCount-1][columnCount];
                int rowIndex = 0;
                for (List<String> row : data) {
                    int colIndex = 0;
                    for (String rowData : row) {
                        dataArray[rowIndex][colIndex++] = rowData;
                    }
                    rowIndex++;
                }
                return dataArray;
            }
            System.err.println("Table name is incorrect");
            return new String[][] {{}};
        } catch (Exception e) {
            e.printStackTrace();
            return new String[][] {{}};
        }
    }
}
```

**Comment by umeshds6** [comment]
Hi friends,
please help me how to to use multiple data providers in selenium Testng

**Comment by krmahadevan** [comment]
@umeshds6 - I would recommend that you post a detailed question on what you are looking for, on the [TestNG forums](https://groups.google.com/forum/#!forum/testng-users)

**Comment by Sai7574** [comment]
String ExcelPath = "./TestData/CheckListExecutionData.xlsx";
	String[] sheets = { "ChecklistExecutionData", "Sheet1", "Sheet2" };
 
	@DataProvider(name = "ChecklistExecutionData")
	public Object[][] testDataSupplier() throws Exception {
		List<Object[]> testDataList = new ArrayList<>();
		for (String sheet : sheets) {
			Excelutil2 excel = new Excelutil2(ExcelPath, sheet);
			for (int i = 1; i <= excel.getRowCount(); i++) {
				HashMap<String, String> testData = excel.getTestDataInMap(i);
				testDataList.add(new Object[] { sheet, testData });
			}
		}
		return testDataList.toArray(new Object[0][]);
	} with this dataprovider how to use different sheets for different @test methods
