### ISSUE TITLE
ITestListener.onTestStart() not called after fail or skip from @BeforeMethod

### ISSUE THREAD

**Issue by sbabcoc** [cbeust/testng#1777]
### TestNG Version
7.0.0-SNAPSHOT (7.0.0-20180409.211215-1)

### Expected behavior
ITestListener.onTestStart() should always be called

### Actual behavior
ITestListener.onTestStart() not called after fail or skip from @BeforeMethod

This is a change in behavior from previous releases. It's definitely open for discussion exactly which listener methods get invoked for skipped tests, but the previous behavior always invoked onTestStart(), and the onTestSkipped() method was the result.

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
```
package org.example;

import static org.testng.Assert.assertTrue;

import java.io.File;
import java.lang.reflect.Method;
import java.util.LinkedList;
import java.util.List;

import org.testng.Assert;
import org.testng.IInvokedMethod;
import org.testng.IInvokedMethodListener2;
import org.testng.ITestContext;
import org.testng.ITestListener;
import org.testng.ITestNGListener;
import org.testng.ITestNGMethod;
import org.testng.ITestResult;
import org.testng.TestNG;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import org.testng.xml.XmlSuite;

public class NewIssueReproTest {
    @Test
    public void reproduceIssue() {
        TestNG testNG = new TestNG();
        testNG.setTestClasses(new Class[]{ExampleClass.class});
        testNG.setConfigFailurePolicy(XmlSuite.FailurePolicy.CONTINUE);
        MyListener listener = new MyListener();
        testNG.addListener((ITestNGListener) listener);
        testNG.run();
        String file = TestNG.class.getProtectionDomain().getCodeSource().getLocation().getFile();
        System.out.println("TestNG v" + new File(file).getParentFile().getName());
        listener.allMsgs.forEach(System.out::println);
        System.out.println("===== TEST MESSAGES ======");
        listener.tstMsgs.forEach(System.out::println);
        System.out.println("===== CONFIG MESSAGES =====");
        listener.cfgMsgs.forEach(System.out::println);
        Assert.assertEquals(listener.tstMsgs.size(), 8);
        Assert.assertEquals(listener.cfgMsgs.size(), 8);
    }

    static class ExampleClass {

        @BeforeMethod
        public void beforeMethod(Method method) {
            if ("test1".equals(method.getName())) {
                throw new AssertionError("Assertion error from [before]");
            }
        }

        @Test
        public void test1() {
            assertTrue(true);
        }

        @Test
        public void test2() {
            assertTrue(true);
        }

        @AfterMethod
        public void afterMethod(Method method) {}
    }

    static class MyListener implements IInvokedMethodListener2, ITestListener {
        List<String> allMsgs = new LinkedList<>();
        List<String> tstMsgs = new LinkedList<>();
        List<String> cfgMsgs = new LinkedList<>();

        @Override
        public void onFinish(ITestContext testContext) {
        }

        @Override
        public void onStart(ITestContext testContext) {
        }

        @Override
        public void onTestFailedButWithinSuccessPercentage(ITestResult testResult) {
            testResult.getMethod().getConstructorOrMethod().getMethod();
            log("testFailedBut", testResult);
        }

        @Override
        public void onTestFailure(ITestResult testResult) {
            log("testFailed", testResult);
        }

        @Override
        public void onTestSkipped(ITestResult testResult) {
            log("testSkipped", testResult);
        }

        @Override
        public void onTestStart(ITestResult testResult) {
            log("testStart", testResult);
        }

        @Override
        public void onTestSuccess(ITestResult testResult) {
            log("testSuccess", testResult);
        }

        @Override
        public void afterInvocation(IInvokedMethod method, ITestResult testResult, ITestContext testContext) {
            log("after", method, testResult);
        }

        @Override
        public void beforeInvocation(IInvokedMethod method, ITestResult testResult, ITestContext testContext) {
            log("before", method, testResult);
        }

        @Override
        public void beforeInvocation(IInvokedMethod method, ITestResult testResult) {
            log("before", method, testResult);
        }

        @Override
        public void afterInvocation(IInvokedMethod method, ITestResult testResult) {
            log("after", method, testResult);
        }
        
        private void log(String prefix, ITestResult testResult) {
            log(prefix, testResult.getMethod(), testResult);
        }
        
        private void log(String prefix, IInvokedMethod method, ITestResult testResult) {
            log(prefix, method.getTestMethod(), testResult);
        }

        private void log(String prefix, ITestNGMethod method, ITestResult testResult) {
            String msg = prefix + "_";
            if (method.isTest()) {
                msg += "test_method: ";
            } else {
                msg += "configuration_method: ";
            }
            msg += method.getMethodName() + parameters(testResult);
            allMsgs.add(msg);
            if (method.isTest()) {
                tstMsgs.add(msg);
            } else {
                cfgMsgs.add(msg);
            }
        }

        private String parameters(ITestResult testResult) {
            Object[] parameters = testResult.getParameters();
            if (parameters != null) {
                StringBuilder builder = new StringBuilder();
                for (Object parameter : parameters) {
                    if (parameter instanceof Method) {
                        builder.append(((Method) parameter).getName());
                    }
                }
                if (builder.length() != 0) {
                    return "[" + builder.toString() + "]";
                }
            }
            return "";

        }
    }
}
```

**Comment by krmahadevan** [comment]
@sbabcoc - This issue contradicts with #911
I have the fix ready, but unless and until we sort out the contradiction, I cannot proceed further. 
There are basically two ways of looking at it.

@juherr @cbeust - Please let me know what we should be doing.

* **Argument 1** - If a configuration method fails, then ideally a test method should not even be started. So `onStart()` would not be invoked.

* **Argument 2** - If a configuration method fails, then the onSkip() is invoked for a test method. Then why not invoke `onStart()` as well, since we did try to start running a test method, but didn't proceed further because the method is skipped.

**Comment by juherr** [comment]
As the 2 behaviors are expected, what if we have a way to configure it?

**Comment by krmahadevan** [comment]
@juherr - You mean via a configuration ? I prefer JVM arguments, but I know both you and @cbeust lean more towards configuration parameter... 😁

**Comment by juherr** [comment]
A configuration in the xml, command line, `TestNG` or jvm arg as you prefer. But the problem with jvm arg is it could be more difficult to share the way to run the tests.

**Comment by krmahadevan** [comment]
@juherr - Agreed on the JVM argument. But why would someone want to configure this on a per test basis ? Listeners are global and so it makes sense for us to bind this behavior to a JVM argument.

**Comment by juherr** [comment]
For example, if a user has an old suite with the old behavior and wants to update TestNG without updating the behavior. But jvm arg is good for me if you prefer it.

**Comment by sbabcoc** [comment]
In the previous behavior, the sequence is:

* onTestStart(testMethod)
* beforeInvocation(testMethod)
* afterInvocation(testMethod)
* onTestSkipped(testMethod)

The revised behavior is:

* onTestSkipped(testMethod)
* beforeInvocation(testMethod)
* afterInvocation(testMethod)

This makes less sense to me, especially in terms of the symmetry of the calls. onTestSkipped() is supposed to be the final disposition, not the entire flow. The "before" and "after" calls feel like an afterthought.

**Comment by juherr** [comment]
+1 for another issue and my remark there will be: why *Invocation if skipped (not invoked)?

**Comment by sbabcoc** [comment]
Issue #911 failed to consider the symmetry of notifications for test execution phases. If the configuration methods run, the tests *always* start. Otherwise, setup that needs to be performed prior to the start of the test will not be executed. onTestStarted and onTestSkipped are bookends for the test method. This is proper symmetry.

**Comment by sbabcoc** [comment]
@juherr The same symmetry issue holds for the beforeInvocation and afterInvocation signals. If the configuration methods run, these need to run, too. What if the client is using listeners to interface to a remote reporting facility? If symmetry is not maintained, disposition reporting for skipped tests will be missing, or could even result in failures due to the missing notifications.

**Comment by sbabcoc** [comment]
The overarching concern behind this issue report is that the change in behavior breaks existing client code. This is a fundamental change to the notifications sent to listeners for skipped tests. What actual problem was being solved? As far as I can tell, issue #911 doesn't describe an actual defect, but is merely instead someone's *opinion* about the notifications that should be sent for skipped tests.

**Comment by krmahadevan** [comment]
@sbabcoc - Not sure what you are hinting at. If there were regressions introduced due to change in behavior, we can have them fixed. Also please be informed that I don't recollect TestNG documenting anywhere the order of listener invocation explicitly. TestNG merely provides a way for users to wire in their callbacks. The listeners were never meant to be anything more than that. 

But we do acknowledge the fact that, people have perhaps built implementations on the assumption that listeners would be invoked in some order (Even among similar listeners TestNG doesn't guarantee order). So we can fix it and also from TestNG 7.0.0 we can even publish the expected order of various listeners so that people exactly know how they are going to be invoked.

For ensuring all of that, is where I was previously asking, please file a separate issue. That way all of the discussion can be isolated to it. 

**Note**

Here when I say order, I am talking about should `beforeInvocation` come first (or) should `onStart()` come first etc.,

If you are aware of any such official TestNG documentation, please help point me to it, and I will use that as a reference to perhaps create a comprehensive document which explains all of these about listeners in general.

**Comment by sbabcoc** [comment]
The product is the spec. You're changing behavior that has existed for some time, and I have yet to see an actual technical issue that's addressed by this change.
I never made any reference to the order in which listeners are called. My description is of the notifications that are sent by the TestNG API to attached listeners.
Also, I made no mention of internal TestNG regressions. My point regards TestNG client code that will be broken by the altered behavior.

**Comment by krmahadevan** [comment]
​@sbabcoc

​We are just going around in circles. TestNG has been in place for a very
long time and is an Open source project. The project has seen committers
come and committers go at different points in time. Everyone tries their
level best to ensure that the experience remains the same. But that effort
is only as effective as whatever tests are in place which provide that
continuous feedback. So every contributor/committer strives their level
best to ensure that the tests don't break with any new additional change.
But if there were no tests that basically provide that feedback then it
becomes that hard to ensure that spec is adhered to.

​Also please be aware that the codebase will continuously evolve as and
when new asks are made by users and so some behaviors may have changed. I
dont have visibility into all those historical aspects and I dont think it
makes any sense for me to sit and debate on all those things.

I am re-iterating what I mentioned earlier. If there is any issue or a
breakage of functionality with respect to what used to work earlier and is
not working right now, please file an issue and we will try to get to it at
the earliest.
Also since we would be adding tests for that bug, it would now act as a
guard to ensure that further breakage is not happening for the same
functionality in question.

I am going to leave this conversation at this level and let you decide what
you would like to do going forward!


​@cbeust / @juherr - Please add your thoughts as well.​

**Comment by juherr** [comment]
Nothing to add! I have the same opinion :)

And at the same time, I'm sure @sbabcoc just want to have a better tool.
So please, create new issues if there are some other breaking changes because we always try to fix them and the current issue will be fixed soon.

**Comment by sbabcoc** [comment]
This report has always been focused on a single issue - a fundamental change to the notifications received by ITestListener instances for skipped tests. A new report would be a duplicate of this one. The behavioral change documented by this report was apparently made based on issue #911, which contains no indication of any actual technical problem. Is there an actual problem being addressed by this behavioral change? If so, it would be helpful to me to have this problem described. If this change is based merely on someone's personal preference, this is insufficient justification for such a fundamental change.
I've documented to longstanding behavior and the revised behavior above. Unless a valid technical argument can be made to support the revised behavior, I suggest that the former behavior should be restored.

**Comment by krmahadevan** [comment]
@sbabcoc - This current issue talks about onStart() not getting called. The PR that I raised deals with it. I am still not able to understand what are you referring to when you say fundamental change to the notifications received by ITestListener instances. Anyways, I don't have anything additional to say than what I have already stated. 

The fix for this bug is already awaiting a merge. So once the fix gets merged, this issue will get closed. If there are any additional issues, request you to please open up a new issue and we will get to it.
