### ISSUE TITLE
Null Pointer Exception in ConfigInvoker.setMethodInvocationFailure

### ISSUE THREAD

**Issue by bc-joshroe** [cbeust/testng#2232]
### TestNG Version
> Note: only the latest version is supported

7.1.0

### Expected behavior
When running tests, ConfigInvoker.setMethodInvocationFailure should not be throwing Null Pointer Exception

### Actual behavior
A Null Pointer Exception is thrown by TestNG:

Exception java.lang.NullPointerException
Message: (none)

Stacktrace:

```
at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1645)
at org.testng.internal.ConfigInvoker.setMethodInvocationFailure(ConfigInvoker.java:488)
at org.testng.internal.ConfigInvoker.recordConfigurationInvocationFailed(ConfigInvoker.java:529)
at org.testng.internal.ConfigInvoker.handleConfigurationFailure(ConfigInvoker.java:441)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:308)
at org.testng.internal.ConfigInvoker.invokeBeforeGroupsConfigurations(ConfigInvoker.java:142)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:518)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

### Is the issue reproductible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

I've been unable to narrow down the exact cause thus far. I believe it might happen when there is an exception in a setup method or parent setup method (while running the tests in parallel).  However I am still looking into it.

Either way, it seems like we should add a null check in java.util.concurrent.ConcurrentHashMap.computeIfAbsent to prevent this issue from happening.  I believe this NPE is covering up the actual exception being thrown by the tests.

**Comment by krmahadevan** [comment]
@bc-joshroe - The code flow kind of makes it difficult for us to understand as to when would would a test method object even come up as null. Can you please share a sample to reproduce the problem ? The issue could be somewhere else and not necessarily here.

**Comment by abunaiquad** [comment]
Hi, I am also getting this error message in testng version 7.00 and 7.1.0, but not 6.14.2 and 6.14.3.

Let's see if I can explain this properly. In our framework, we test for different api_version (ie v1, v2, etc). And the same test method isn't supported on all api_version, so we implemented IMethodInterceptor to filter out test that is supported for current api_version that is executing.

Using testng 7.0.0 and 7.1.0, I noticed that we get this error (ConfigInvoker.setMethodInvocationFailure) on tests that aren't supposed to be executing on current api_version.

Hope it helps.

**Comment by bc-joshroe** [comment]
@krmahadevan - So far, I have been unable to reproduce it through sample code that I can share.  I will try a little more.  I am able to consistently reproduce it on a small internal test suite with 11 tests running in parallel.  I believe it may be a race condition with parallel runs, because out of the 11 tests, 1 always fails with this error (every time), but it seems to be random as to which one fails.

**Comment by krmahadevan** [comment]
@bc-joshroe 

> I am able to consistently reproduce it on a small internal test suite with 11 tests running in parallel.

As a start, can you please try creating a sample project which exactly looks like what your tests do, but without any of your internal logic. You can obfuscate all your internal logic and replace them with sys out statements.

I would really like to see the following mainly:

1. How many test classes were there?
2. What does your testng suite xml file look like ?
3. The stack trace seems to suggest that you are perhaps running via groups. Is that the case ?
4. What all configuration methods exist and do they also belong to a group.

Perhaps these could help you with creating a reproducible sample as well ?

**Comment by bc-joshroe** [comment]
@krmahadevan  - After a bunch of digging, I believe I have a reproducible case for you.  The short version is that it look like this NPE is a side effect of this bug (which is still occurring): https://github.com/cbeust/testng/issues/2152

The sample tests are here:


```
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;


@Test(groups={"Group1", "Group2", "Group3"})
public class SampleTest {
    private int variable = 0;

    @BeforeClass
    public void setUp() throws Exception {
        System.out.println("Setup1 variable1=" + variable++);
    }

    @AfterMethod
    public void tearDown() throws Exception {
        System.out.println("Teardown1 variable1=" + variable++);
    }

    /**
     * Data Provider for Patient Create tests
     * @return
     */
    @DataProvider(name="patientCreateData")
    public Object[][] patientCreateData() {
        return new Object[][] {
                // First Name - Positive
                /* Minimum Length */ {"Test1"},
                /* Maximum Length */ {"Test2"},
        };
    }

    /**
     * Verify the response from the Patient Create API
     * @param test
     */
    @Test(dataProvider="patientCreateData")
    public void testPatientCreate(String test) {
        System.out.println(test + " variable1=" + variable++);
    }
}
```



```
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;


@Test(groups={"Group1", "Group2", "Group3"})
public class SampleTest2 {
    private int variable = 0;

    @BeforeClass
    public void setUp() throws Exception {
        System.out.println("Setup2 variable2=" + variable++);
        if (variable == 4) {
            throw new Exception("Exception!");
        }
    }

    @AfterMethod
    public void tearDown() throws Exception {
        System.out.println("Teardown2 variable2=" + variable++);
    }

    /**
     * Data Provider for tests
     * @return
     */
    @DataProvider(name="testData")
    public Object[][] patientCreateData() {
        return new Object[][] {
                {"Test3"},
                {"Test4"},
        };
    }

    /**
     * Verify the value
     * @param test
     */
    @Test(dataProvider="testData")
    public void testPatientCreate(String test) {
        System.out.println(test + " variable2=" + variable++);
    }
}
```

I run these in parallel at the class level using `include name = "Group2"`
`parallel="classes" thread-count="256" configfailurepolicy="continue"`


The output looks like this:

> Setup2 variable2=0
> Setup1 variable1=0
> Setup2 variable2=1
> Teardown2 variable2=2
> Setup1 variable1=1
> Teardown1 variable1=2
> Setup2 variable2=3
> Test1 variable1=3
> Teardown1 variable1=4
> Test2 variable1=5
> Teardown1 variable1=6

Notice that the setup is called multiple times per test and is called out of order (for the class).  I would expect it to look something more like this at the class level:
> Setup1 variable1=0
> Test1 variable1=1
> Teardown1 variable1=2
> Setup1 variable1=3
> Test1 variable1=4
> Teardown1 variable1=5

If you run these tests, you will see the Null Pointer Exception mentioned above in this issue because I am throwing an error randomly in the setup of one of the test classes.

Hope that helps.  Please let me know if you need any more info.  Thanks!

**Comment by krmahadevan** [comment]
@bc-joshroe - I have not been able to reproduce the problem. I have created a sample project that uses TestNG `7.1.0` and uses the code that you shared.

I also created two suite xml files.

1. `groups_at_suite_level.xml` - Contains the `<group>` tag at the `<suite>` level. (This is by default selected)
2. `groups_at_test_level.xml` - Contains the `<group>` tag at the `<test>` level. [ This can be selected by running `mvn clean test -DsuiteFile=groups_at_test_level.xml`

In either case, I am not able to simulate the NPE that you are experiencing. 

Can you please try using this attached project and see if there are any changes needed to be made to reproduce the problem ?

[issue_2232.zip](https://github.com/cbeust/testng/files/4184004/issue_2232.zip)

**Comment by bc-joshroe** [comment]
@krmahadevan  - I updated the groups_at_test_level.xml file to be:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite thread-count="256" configfailurepolicy="continue" verbose="2" name="2232_suite_groups_at_test_level"
  parallel="classes">
  <test thread-count="256" verbose="2" name="2232_test" parallel="classes">
    <groups>
      <run>
        <include name="Group2"/> <exclude name="Broken"/>
      </run>
    </groups>
    <!--classes>
      <class name="com.rationaleemotions.SampleTest"/>
      <class name="com.rationaleemotions.SampleTest2"/>
    </classes-->

    <packages>
      <package name="com.rationaleemotions.*" />
    </packages>
  </test> <!-- 2232_test -->
</suite> <!-- 2232_suite -->
```

and ran using this command:
```
mvn clean install test -Dsurefire.suiteXmlFiles='src/test/resources/groups_at_test_level.xml'
```

This is the output I got (might need to run it a few times to make sure the exception is called):
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
...
... TestNG 7.1.0 by Cédric Beust (cedric@beust.com)
...

Setup1 variable1=0
Setup2 variable2=0
Setup2 variable2=1
Teardown2 variable2=2
Setup1 variable1=1
Teardown1 variable1=2
Test1 variable1=3
Setup2 variable2=3
Teardown1 variable1=4
Test2 variable1=5
Teardown1 variable1=6
FAILED CONFIGURATION: setUp
java.lang.Exception: Exception!
	at com.rationaleemotions.SampleTest2.setUp(SampleTest2.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
	at org.testng.internal.ConfigInvoker.invokeBeforeGroupsConfigurations(ConfigInvoker.java:142)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:518)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

FAILED CONFIGURATION: tearDown
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1645)
	at org.testng.internal.ConfigInvoker.setMethodInvocationFailure(ConfigInvoker.java:488)
	at org.testng.internal.ConfigInvoker.recordConfigurationInvocationFailed(ConfigInvoker.java:529)
	at org.testng.internal.ConfigInvoker.handleConfigurationSkip(ConfigInvoker.java:399)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:268)
	at org.testng.internal.ConfigInvoker.invokeBeforeGroupsConfigurations(ConfigInvoker.java:142)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:518)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

PASSED: test1("Test1")
PASSED: test1("Test2")
FAILED: test2
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1645)
	at org.testng.internal.ConfigInvoker.setMethodInvocationFailure(ConfigInvoker.java:488)
	at org.testng.internal.ConfigInvoker.recordConfigurationInvocationFailed(ConfigInvoker.java:529)
	at org.testng.internal.ConfigInvoker.handleConfigurationFailure(ConfigInvoker.java:441)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:308)
	at org.testng.internal.ConfigInvoker.invokeBeforeGroupsConfigurations(ConfigInvoker.java:142)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:518)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


===============================================
    2232_test
    Tests run: 3, Failures: 1, Skips: 0
    Configuration Failures: 2, Skips: 0
===============================================

[ERROR] Tests run: 5, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 0.516 s <<< FAILURE! - in TestSuite
[ERROR] setUp(com.rationaleemotions.SampleTest2)  Time elapsed: 0.003 s  <<< FAILURE!
java.lang.Exception: Exception!
	at com.rationaleemotions.SampleTest2.setUp(SampleTest2.java:17)

[ERROR] tearDown(com.rationaleemotions.SampleTest2)  Time elapsed: 0.004 s  <<< FAILURE!
java.lang.NullPointerException

[ERROR] test2(com.rationaleemotions.SampleTest2)  Time elapsed: 0.004 s  <<< FAILURE!
java.lang.NullPointerException

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   SampleTest2.setUp:17  Exception!
[ERROR]   SampleTest2.tearDown » NullPointer
[ERROR]   SampleTest2.test2 » NullPointer
[INFO] 
[ERROR] Tests run: 5, Failures: 3, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.518 s
[INFO] Finished at: 2020-02-20T13:37:21-08:00
[INFO] ------------------------------------------------------------------------

```

Please let me know if you need any further information.  Thanks!

**Comment by krmahadevan** [comment]
@bc-joshroe - I still haven't been able to reproduce the NPE :( 

I been trying to recreate it on both Mac and Ubuntu in the following modes

1. IntelliJ
2. eclipse
3. Using Maven command line.

The NPE still doesn't come up. What JDK version and flavor are you using ? How are you running the tests ? Your output seems to suggest that its via maven command line.

But the following is what I am curious about

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
...
... TestNG 7.1.0 by Cédric Beust (cedric@beust.com)
...
```

There's a discrepancy with TestNG `7.1.0` owing to which the version displayed in the banner should have been always `7.0.1` but in your case its showing as `7.1.0`.

Can you please help clean up `~/.m2/repository/org/testng` folder, redo a `mvn dependency:resolve` and try again ?

This is how you should be seeing the output as 

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
...
... TestNG 7.0.1 by CÃ©dric Beust (cedric@beust.com)
...
```

**Comment by bc-joshroe** [comment]
@krmahadevan  - I am using this Java version (on Mac):
```
$ java -version
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
```

I am able to reproduce the NPE in ConfigInvoker.setMethodInvocationFailure on both Mac and Linux.

I deleted everything in the `~/.m2/repository/org/testng` folder, then ran `mvn dependency:resolve`.  Then I ran the tests using this command on the command line (Mac):
`mvn clean install test -Dsurefire.suiteXmlFiles='src/test/resources/groups_at_test_level.xml'`

and got this output:

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< com.rationaleemotions:issue_2232 >------------------
[INFO] Building issue_2232 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ issue_2232 ---
[INFO] Deleting /issue_2232-2/target
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ issue_2232 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /issue_2232-2/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ issue_2232 ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ issue_2232 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ issue_2232 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /issue_2232-2/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ issue_2232 ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
...
... TestNG 7.1.0 by Cédric Beust (cedric@beust.com)
...

Setup1 variable1=0
Setup2 variable2=0
Setup2 variable2=1
Teardown2 variable2=2
Setup1 variable1=1
Teardown1 variable1=2
Test1 variable1=3
Setup2 variable2=3
Teardown1 variable1=4
Test2 variable1=5
Teardown1 variable1=6
FAILED CONFIGURATION: setUp
java.lang.Exception: Exception!
	at com.rationaleemotions.SampleTest2.setUp(SampleTest2.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
	at org.testng.internal.ConfigInvoker.invokeBeforeGroupsConfigurations(ConfigInvoker.java:142)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:518)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

FAILED CONFIGURATION: tearDown
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1645)
	at org.testng.internal.ConfigInvoker.setMethodInvocationFailure(ConfigInvoker.java:488)
	at org.testng.internal.ConfigInvoker.recordConfigurationInvocationFailed(ConfigInvoker.java:529)
	at org.testng.internal.ConfigInvoker.handleConfigurationSkip(ConfigInvoker.java:399)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:268)
	at org.testng.internal.ConfigInvoker.invokeBeforeGroupsConfigurations(ConfigInvoker.java:142)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:518)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

PASSED: test1("Test1")
PASSED: test1("Test2")
FAILED: test2
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1645)
	at org.testng.internal.ConfigInvoker.setMethodInvocationFailure(ConfigInvoker.java:488)
	at org.testng.internal.ConfigInvoker.recordConfigurationInvocationFailed(ConfigInvoker.java:529)
	at org.testng.internal.ConfigInvoker.handleConfigurationFailure(ConfigInvoker.java:441)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:308)
	at org.testng.internal.ConfigInvoker.invokeBeforeGroupsConfigurations(ConfigInvoker.java:142)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:518)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


===============================================
    2232_test
    Tests run: 3, Failures: 1, Skips: 0
    Configuration Failures: 2, Skips: 0
===============================================

[ERROR] Tests run: 5, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 0.611 s <<< FAILURE! - in TestSuite
[ERROR] setUp(com.rationaleemotions.SampleTest2)  Time elapsed: 0.003 s  <<< FAILURE!
java.lang.Exception: Exception!
	at com.rationaleemotions.SampleTest2.setUp(SampleTest2.java:17)

[ERROR] tearDown(com.rationaleemotions.SampleTest2)  Time elapsed: 0.004 s  <<< FAILURE!
java.lang.NullPointerException

[ERROR] test2(com.rationaleemotions.SampleTest2)  Time elapsed: 0.004 s  <<< FAILURE!
java.lang.NullPointerException

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   SampleTest2.setUp:17  Exception!
[ERROR]   SampleTest2.tearDown » NullPointer
[ERROR]   SampleTest2.test2 » NullPointer
[INFO] 
[ERROR] Tests run: 5, Failures: 3, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.017 s
[INFO] Finished at: 2020-02-21T11:08:06-08:00
[INFO] ------------------------------------------------------------------------
```

What command are you using to run the tests?  What is the output you are seeing?  You may have to run the tests 4 or 5 times to see the error.

Also, did you update the xml file mentioned above?

Thanks.

**Comment by krmahadevan** [comment]
@bc-joshroe - 

On my MAC, I am running on 

```
11:51 $ java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```

And on my Ubuntu VM, I am running on 

```
$:~/issue_2232$ java --version
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu119.10.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu119.10.1, mixed mode, sharing)
```
Can you try upgrading your JDK to latest version in JDK8 ? You seem to be on an older version (Just trying to negate any bugs in JDK that may be causing this)


> What command are you using to run the tests? 

`mvn clean test`

> What is the output you are seeing? You may have to run the tests 4 or 5 times to see the error.

I can simulate the test configuration throwing the `Exception` , but I cant simulate TestNG triggering an NPE (which is what you are seeing.

```
$ mvn clean test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< com.rationaleemotions:issue_2232 >------------------
[INFO] Building issue_2232 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ issue_2232 ---
[INFO] Deleting /home/krmahadevan/issue_2232/target
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ issue_2232 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/krmahadevan/issue_2232/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ issue_2232 ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ issue_2232 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ issue_2232 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/krmahadevan/issue_2232/target/test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ issue_2232 ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
...
... TestNG 7.0.1 by CÃ©dric Beust (cedric@beust.com)
...

Setup1 variable1=0
Setup2 variable2=0
Setup1 variable1=1
Teardown1 variable1=2
Setup2 variable2=1
Teardown2 variable2=2
Setup1 variable1=3
Test1 variable1=4
Teardown1 variable1=5
Setup2 variable2=3
Teardown1 variable1=6
Test2 variable1=7
Teardown2 variable2=4
Teardown1 variable1=8
Setup1 variable1=9
Teardown1 variable1=10
Setup2 variable2=5
Teardown2 variable2=6
Setup1 variable1=11
Teardown1 variable1=12
Teardown2 variable2=7
Setup2 variable2=8
FAILED CONFIGURATION: setUp
java.lang.Exception: Exception!
	at com.rationaleemotions.SampleTest2.setUp(SampleTest2.java:20)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
	at org.testng.internal.ConfigInvoker.invokeBeforeGroupsConfigurations(ConfigInvoker.java:142)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:518)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

SKIPPED CONFIGURATION: @AfterMethod tearDown
SKIPPED CONFIGURATION: @AfterMethod tearDown
PASSED: test1("Test1")
PASSED: test1("Test2")
SKIPPED: test2
java.lang.Exception: Exception!
	at com.rationaleemotions.SampleTest2.setUp(SampleTest2.java:20)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
	at org.testng.internal.ConfigInvoker.invokeBeforeGroupsConfigurations(ConfigInvoker.java:142)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:518)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

SKIPPED: test2
java.lang.Exception: Exception!
	at com.rationaleemotions.SampleTest2.setUp(SampleTest2.java:20)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
	at org.testng.internal.ConfigInvoker.invokeBeforeGroupsConfigurations(ConfigInvoker.java:142)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:518)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)


===============================================
    2232_test
    Tests run: 4, Failures: 0, Skips: 2
    Configuration Failures: 1, Skips: 2
===============================================

[ERROR] Tests run: 7, Failures: 1, Errors: 0, Skipped: 4, Time elapsed: 0.938 s <<< FAILURE! - in TestSuite
[ERROR] setUp(com.rationaleemotions.SampleTest2)  Time elapsed: 0.002 s  <<< FAILURE!
java.lang.Exception: Exception!
	at com.rationaleemotions.SampleTest2.setUp(SampleTest2.java:20)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   SampleTest2.setUp:20  Exception!
[INFO]
[ERROR] Tests run: 5, Failures: 1, Errors: 0, Skipped: 2
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.674 s
[INFO] Finished at: 2020-02-23T12:03:46+05:30
[INFO] ------------------------------------------------------------------------
```



 > Also, did you update the xml file mentioned above?

Yes I have added the `exclude` tag.

**Comment by bc-joshroe** [comment]
@krmahadevan 
I just updated my Java to the latest version:
```issue_2232-2$ javac -version
javac 1.8.0_241```

and re-ran the tests using:
```mvn clean install test -Dsurefire.suiteXmlFiles='src/test/resources/groups_at_test_level.xml'```

I got the same output as my comment above.  Can you retry running with this command:
```mvn clean install test -Dsurefire.suiteXmlFiles='src/test/resources/groups_at_test_level.xml'```

**Comment by krmahadevan** [comment]
@bc-joshroe - I still haven't been able to reproduce this issue at my end. 

Can you please try to recreate this using the latest changes from the codebase ?

You can follow the below steps for doing that.

1. Clone the TestNG project.
2. Open `build.gradle.kts`
3. Add `maven` after [this](https://github.com/cbeust/testng/blob/master/build.gradle.kts#L55) line
4. Now run `./gradlew clean install` 
5. Step (4) will deploy `7.1.1-SNAPSHOT` to your local maven repository
6. Update your dependency to `7.1.1-SNAPSHOT` and try your scenario once again and let me know how it goes.

**Comment by Maksim-Laitan** [comment]
I created Sample https://github.com/Maksim-Laitan/SampleExampleForTestNG if I correctly understand what must be in this sample.
