### ISSUE TITLE
TestNG priority number results in console displays Zeros "0" for all methods

### ISSUE THREAD

**Issue by cyberdome** [cbeust/testng#978]
Hello World!,

  For TestNG when you execute priority test cases, so for example, 1, 2, 3, then the results should display as per priority the correct number. But instead it is showing Zeros for every result.  Just FYI.

**Comment by juherr** [comment]
Could you share some code ?

**Comment by cyberdome** [comment]
[SuiteRunner] Created 1 TestRunners
[TestRunner] Running test Test on 1  classes,  included groups:[] excluded groups:[]
===== Test class
selenium.TestNG
  @BeforeClass TestNG.login()[pri:0, instance:selenium.TestNG@129a8472]
    @Test TestNG.fundingCircleTest()[pri:0, instance:selenium.TestNG@129a8472]
  @AfterClass TestNG.logout()[pri:0, instance:selenium.TestNG@129a8472]

Take a closer look at the prirority numbers. they both are same as Zero "0".  When executing using XML files or using TestNG,  The priority shows as 0,   I hope this makes sense.  

Hope this was helpful.

**Comment by juherr** [comment]
Try with 6.9.10

**Comment by juherr** [comment]
Duplicate of #764

**Comment by cyberdome** [comment]
Cannot update TestNG with eclipse. This is a plugin provided by Eclipse. Please, can you push an update in the Eclipse marketplace. thanks. :)

**Comment by juherr** [comment]
What is your plugin version ?

**Comment by cyberdome** [comment]
TestNG **6.9.6** by CÃ©dric Beust (cedric@beust.com)

**Comment by juherr** [comment]
The issue is fixed latest.

**Comment by cyberdome** [comment]
The latest version is NOT available in Eclipse marketplace. Are you able to deploy the latest build in Eclipse Marketplace.

**Comment by juherr** [comment]
Ping @missedone

**Comment by missedone** [comment]
hi @cyberdome 
the latest TestNG Eclipse Plugin is *6.9.10.201512240000*.
which version did you expect?

i'm not sure when will 6.9.11 of plugin being release, so if you want to use the latest TestNG 6.9.11-SNAPSHOT, you can specify 6.9.11-SNAPSHOT in your pom.xml if the project is managed by Maven. or you can download the latest SNAPSHOT jar file and put it onto your project classpath ...

**Comment by cyberdome** [comment]
I have the latest TestNG version on my eclipse after much troubleshooting finally.  But when I execute my XML test case file. It is still showing TestNG 6.9.6 by CÃ©dric Beust inside my console.  First, I installed TestNG via Eclipse Marketpace and then I installed the latest TestNG using "Install New Software" option.  Maybe, mixing it cause something?

**Comment by missedone** [comment]
OK, let's solve them one by one.
1. sounds like your test cases were running with the embedded TestNG of plugin, if you have the latest TestNG version on your project classpath, you can enable option "Use Project TestNG jar" to use your project specific TestNG jar rather than plugin embedded one. see more instructions here: http://testng.org/doc/eclipse.html#eclipse-preferences
2. if you want to install the latest TestNG plugin, you can uninstall the current one, and re-install either from Marketplace or "Install New Software..."

**Comment by cyberdome** [comment]
@missedone  Second option works best.  If any1 else has this problem. They can go with option 2.  So, the marketplace has the older version of TestNG which they need to deploy the newest version into it.  Just FYI.
